In [1]:
import pandas as pd
import numpy as np

In [55]:
SafRev = pd.read_csv("/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/Automating-Boring-Stuff-with-Python/Safaricom reviews/SafaricomReviews.csv")
SafRev

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Brand ambassador,5.0,"Aug 8, 2025","Former employee, more than 1 year","Flexible hours, supportive team, good training...","Inconsistent hours, limited career growth, com..."
1,Senior mobile developer,4.0,"Jul 28, 2025","Current contractor, more than 1 year",Great for gaining experience on large scale en...,A lot of shifting priorities
2,Project manager,4.0,"Jul 15, 2025","Former employee, more than 3 years",Strong support for professional growth through...,Occasional tight deadlines and high-pressure t...
3,Ict technician,5.0,"Jul 18, 2025",Former employee,the working experience was good,there are no major drawbacks i can talk about
4,Intern,5.0,"Jul 15, 2025","Former intern, less than 1 year",Great work environment. Regular bonuses.,None I can think of
...,...,...,...,...,...,...
1405,Anonymous employee,3.0,"Mar 7, 2022","Current employee, more than 1 year",A good place to work,Being overworked and under high pressure
1406,Intern,4.0,"Apr 8, 2022","Former intern, less than 1 year",Good Benefits and Minimal Workload.,Poor structure for internship programme.
1407,Internship,5.0,"Jun 13, 2022",Current intern,Good experience working at safaricom,Could pay interns better atleast
1408,Senior ux designer,2.0,"Jun 20, 2022",Former employee,Good work place to work in Kenya,No cons here in kenya
1409,Intern,5.0,"Aug 16, 2022",Current intern,Good Salary for an intern,none that I came across

In [56]:
# EDA on the data
def display(x):
    print("Displays the rows and columns in the dataset")
    print("============================================")
    Rows, col = x.shape
    print(f"Rows: {Rows} Columns: {col}")
    print()
    print("Displays data columns")
    print("============================================")
    print(x.columns)
    print()
    print("Returns the data information")
    print("============================================")
    print(x.info)
    print()
    print("Returns the information in more details")
    print("============================================")
    print(x.describe())
    print()
    print("The data type")
    print("============================================")
    print(x.dtypes)
    print()
    print("The number of null values in the dataset")
    print("============================================")
    print(x.isna().sum())
display(SafRev)

Displays the rows and columns in the dataset
============================================
Rows: 1410 Columns: 6

Displays data columns
============================================
Index(['Job Title', 'Job Ratings', 'time', 'JobStatus', 'Pros', 'Cons'], dtype='object')

Returns the data information
============================================
<bound method DataFrame.info of                     Job Title  Job Ratings          time  \
0            Brand ambassador          5.0   Aug 8, 2025
1     Senior mobile developer          4.0  Jul 28, 2025
2             Project manager          4.0  Jul 15, 2025
3              Ict technician          5.0  Jul 18, 2025
4                      Intern          5.0  Jul 15, 2025
...                       ...          ...           ...
1405       Anonymous employee          3.0   Mar 7, 2022
1406                   Intern          4.0   Apr 8, 2022
1407               Internship          5.0  Jun 13, 2022
1408       Senior ux designer          2.0  Jun 20, 2022
1409                   Intern          5.0  Aug 16, 2022

                                 JobStatus  \
0        Former employee, more than 1 year
1     Current contractor, more than 1 year
2       Former employee, more than 3 years
3                          Former employee
4          Former intern, less than 1 year
...                                    ...
1405    Current employee, more than 1 year
1406       Former intern, less than 1 year
1407                        Current intern
1408                       Former employee
1409                        Current intern

                                                   Pros  \
0     Flexible hours, supportive team, good training...
1     Great for gaining experience on large scale en...
2     Strong support for professional growth through...
3                       the working experience was good
4              Great work environment. Regular bonuses.
...                                                 ...
1405                               A good place to work
1406                Good Benefits and Minimal Workload.
1407               Good experience working at safaricom
1408                   Good work place to work in Kenya
1409                          Good Salary for an intern

                                                   Cons
0     Inconsistent hours, limited career growth, com...
1                          A lot of shifting priorities
2     Occasional tight deadlines and high-pressure t...
3         there are no major drawbacks i can talk about
4                                   None I can think of
...                                                 ...
1405           Being overworked and under high pressure
1406           Poor structure for internship programme.
1407                   Could pay interns better atleast
1408                              No cons here in kenya
1409                            none that I came across

[1410 rows x 6 columns]>

Returns the information in more details
============================================
       Job Ratings
count  1410.000000
mean      4.238298
std       0.861581
min       1.000000
25%       4.000000
50%       4.000000
75%       5.000000
max       5.000000

The data type
============================================
Job Title       object
Job Ratings    float64
time            object
JobStatus       object
Pros            object
Cons            object
dtype: object

The number of null values in the dataset
============================================
Job Title      0
Job Ratings    0
time           0
JobStatus      0
Pros           0
Cons           0
dtype: int64

In [17]:
# printing the first 20 elements on the dataset
SafRev.head(20)

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Brand ambassador,5.0,"Aug 8, 2025","Former employee, more than 1 year","Flexible hours, supportive team, good training...","Inconsistent hours, limited career growth, com..."
1,Senior mobile developer,4.0,"Jul 28, 2025","Current contractor, more than 1 year",Great for gaining experience on large scale en...,A lot of shifting priorities
2,Project manager,4.0,"Jul 15, 2025","Former employee, more than 3 years",Strong support for professional growth through...,Occasional tight deadlines and high-pressure t...
3,Ict technician,5.0,"Jul 18, 2025",Former employee,the working experience was good,there are no major drawbacks i can talk about
4,Intern,5.0,"Jul 15, 2025","Former intern, less than 1 year",Great work environment. Regular bonuses.,None I can think of
5,Site reliability engineer,4.0,"Jul 14, 2025","Current contractor, more than 1 year",RTO policy 3 days in the office,Workload may be too much sometime
6,Software qa engineer,3.0,"Jul 13, 2025","Former contractor, more than 3 years",Opportunities for growth\nGood company \nGreat...,Tough management \nExtreme work conditions (pr...
7,Customer service,4.0,"Jul 8, 2025","Former intern, less than 1 year",Good place to work and grow career-wise,Is place that offers carrier growth
8,Customer service representative,3.0,"Jul 3, 2025",Current employee,Job security\nBonus is available,No growth\nCompensation for customer care is n...
9,Ran engineer,4.0,"Jul 6, 2025",Former employee,Conducive work environment for employees growth,Have to meet strict deadlines
10,Territory development representative (tdr),4.0,"Jun 28, 2025","Current employee, more than 1 year",Salaries paid on time\nFamiliar route plan,Working via agency\nNo room for growth
11,Telesales agent,5.0,"Jun 26, 2025",Former employee,Good work environment and aesthetics,Corporate work pressure and politics
12,Customer service representative,4.0,"May 25, 2025","Former contractor, more than 1 year",Safaricom really cares about her employees' we...,How I wish they could intervene in the pay and...
13,Junior software developer,5.0,"Jun 7, 2025",Former employee,Good work-life balance and supportive team env...,Limited advancement opportunities and outdated...
14,Sr. manager it,5.0,"Jun 5, 2025",Former employee,"As an employer, offers significant advantages ...","High-pressure, competitive, and sometimes bure..."
15,Software developer,2.0,"Jun 18, 2025","Current contractor, more than 3 years",I really don't have any pros for them. Hasn't ...,no work life balance.\nscalling is almost impo...
16,Ict technician,4.0,"Jun 20, 2025","Current employee, less than 1 year",you Offer the best services,there are No cons about your performance
17,Intern,5.0,"Jun 5, 2025","Former intern, less than 1 year",They try to help interns and the managers are ...,It requires to put a lot effort and sometimes ...
18,Internship,5.0,"Jun 16, 2025",Former intern,Learning and skill building on enterprise leve...,None that I noticed. Good working place.
19,Senior software engineer,5.0,"Jun 11, 2025",Current contractor,to be updated at a later time,none i can think of right now

In [18]:
# printing the last 20 elements on the dataset
SafRev.tail(20)

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
1390,Customer experience executive,5.0,"Oct 20, 2019","Current employee, more than 8 years",Safaricom PLC is a great employer,Career growth is limited
1391,Software engineer,3.0,"Feb 25, 2020","Former contractor, more than 3 years","Average Pay, Nice Projects, Highly engaging","Excess Work hours, Tight Deadlines"
1392,Product manager,5.0,"Oct 30, 2020","Former employee, more than 3 years","Good employer, great environment. Good","Pressure , though performance based"
1393,Engineer,4.0,"Dec 9, 2020","Current employee, more than 1 year",Great team to work with.,High pressure to meet deadlines
1394,Full stack developer,3.0,"Dec 15, 2020",Former employee,nice working with safaricom man,lots of mistakes from them ni wezi
1395,Software engineer,4.0,"Dec 26, 2020","Current employee, more than 3 years",Wonderful place to work as usual,No comment on the issue
1396,Network optimization engineer,5.0,"Feb 3, 2021",Current employee,Very good terms of employment,Slow career growth in technology
1397,Customer experience executive,5.0,"Feb 22, 2021","Former employee, more than 5 years",Good compensation. Diversity and Inclusion,Limited growth within 5 years
1398,Customer experience representative,2.0,"Mar 11, 2021",Former contractor,Company name is the only big thing,"No exposure,to contracted stuff controlling boss"
1399,Information technology,3.0,"Apr 14, 2021",Former temporary employee,efficient in communication sector in Kenya,luring customers to buy their bundles
1400,Legal officer,3.0,"May 13, 2021","Current employee, more than 5 years","Good salary, environment, benefits, offices ar...","Bad bosses, no career advancement"
1401,Telecommunications engineering specialist,4.0,"Jun 13, 2021","Current contractor, more than 8 years",Excellent company to be in,A lot tasks are in place
1402,Customer care representative,2.0,"Jun 19, 2021",KEY NOT FOUND: jobLine.seasonal-former,good company very efficient and fast,poor wadges and late payment rates
1403,Sales representative,5.0,"Oct 4, 2021",Current contractor,Effective communication\r\nTeam work\r\nCoachi...,Growth opportunities are not clear
1404,Account manager,4.0,"Jan 26, 2022",Current employee,Safaricom has good medical benefits,Safaricom Hr processes are very bureacratic
1405,Anonymous employee,3.0,"Mar 7, 2022","Current employee, more than 1 year",A good place to work,Being overworked and under high pressure
1406,Intern,4.0,"Apr 8, 2022","Former intern, less than 1 year",Good Benefits and Minimal Workload.,Poor structure for internship programme.
1407,Internship,5.0,"Jun 13, 2022",Current intern,Good experience working at safaricom,Could pay interns better atleast
1408,Senior ux designer,2.0,"Jun 20, 2022",Former employee,Good work place to work in Kenya,No cons here in kenya
1409,Intern,5.0,"Aug 16, 2022",Current intern,Good Salary for an intern,none that I came across

In [19]:
# printing the random sample of 20 elements
SafRev.sample(20)

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
1304,Research associate,4.0,"Jul 20, 2021",Current employee,good working conditions and overall pay.,the schedule is not flexible.
34,Sr. manager it,5.0,"Jun 5, 2025",Former employee,"As an employer, offers significant advantages ...","High-pressure, competitive, and sometimes bure..."
1382,Customer service representative,5.0,"Feb 5, 2022",Current employee,Salo comes on time sometimes,Mistreating employees who are on contract
454,Solutions architect,5.0,"Nov 19, 2023","Former employee, more than 1 year",Flexibility of work and maximum benefits,Too much work load especially weekends
796,Government affairs manager,5.0,"Oct 15, 2017","Current employee, more than 5 years","Innovative, vibrant place to work with opport...",The rating sysyem is okay though I think the b...
42,Frontend developer,4.0,"May 22, 2025","Current employee, more than 3 years",- Very friendly and easy to work with colleagu...,- Too much focus on short term goals\n- work o...
99,Internship,4.0,"Mar 14, 2025",Current intern,It's good. I enjoyed my time there.,They should pay more to the interns.
1371,Operations manager,5.0,"Apr 27, 2021",Current employee,Lovely best interesting experience good people.,"Busy,busy busy busy busy busy"
260,Internship,4.0,"Aug 6, 2024","Current intern, less than 1 year",Great Perks\nAwesome Staff\nRevolutionary lead...,Bureaucracy in some of the processes
1400,Legal officer,3.0,"May 13, 2021","Current employee, more than 5 years","Good salary, environment, benefits, offices ar...","Bad bosses, no career advancement"
779,Quality analyst,2.0,"Mar 28, 2021","Former employee, more than 3 years",Yearly Bonus \r\nWork from home \r\nGreat trai...,Contract workers are overworked and underpaid ...
372,Internship,5.0,"Feb 27, 2024","Current intern, less than 1 year",Career growth allowing for better opportunities,High competition for places in the company
1363,Software developer intern,4.0,"Oct 4, 2020","Current intern, less than 1 year","Amazing Team, Cool work culture","Slow decision-making process, Too much micro-m..."
119,Software engineer,5.0,"Feb 12, 2025","Current employee, more than 1 year",Hospitable and supportive in career and person...,Very busy and no overtime pay
1012,Digital product manager,4.0,"Aug 20, 2020","Current employee, more than 3 years",Interesting new idea come through the door all...,slow adoption of new ideas by the business
1126,Solutions architect,4.0,"Aug 20, 2019","Current contractor, more than 3 years",Good work environment\r\nAwesome people to wor...,No good flow of work
1360,Customer support representative,5.0,"Aug 20, 2020",Current employee,"Amazing company, good support to employees",None at the moment .
1295,Intern,4.0,"Feb 1, 2021","Current intern, more than 1 year",Fantastic learning and growth opportunities,Highly competitive and fast paced environment ...
696,Software engineer,5.0,"Jan 21, 2023",Former employee,Best tech company in Kenya,Relatively lower pay compared to multinational...
375,Customer service representative,5.0,"Mar 11, 2024","Current employee, more than 5 years",Flexible work environment\nCompetitive salary,Not applicable\nNot applicable \nNot applicable

# Data cleaning.

In [20]:
column1 = SafRev["Job Title"]
column1

0              Brand ambassador
1       Senior mobile developer
2               Project manager
3                Ict technician
4                        Intern
                 ...
1405         Anonymous employee
1406                     Intern
1407                 Internship
1408         Senior ux designer
1409                     Intern
Name: Job Title, Length: 1410, dtype: object

In [21]:
SafRev.isna().sum()

Job Title      0
Job Ratings    0
time           0
JobStatus      0
Pros           0
Cons           0
dtype: int64

In [22]:
# dropping dublicate values
SafRev.dropna(inplace=True)

In [57]:
# changing the datatype of the time column
SafRev['time'] = pd.to_datetime(SafRev['time'], format='%b %d, %Y')

In [58]:
# Rename the headers
SafRev.rename(columns={"Job Title":"Job Title", "Job Ratings":"Job Rating", "time":"Time", "JobStatus":"Job Status",
                      "Pros":"Pros","Cons":"Cons"},inplace=True)

In [77]:
SafRev["Job Title"].unique()

array(['Brand Ambassador', 'Senior Mobile Developer', 'Project Manager',
       'Ict Technician', 'Intern', 'Site Reliability Engineer',
       'Software Qa Engineer', 'Customer Service',
       'Customer Service Representative', 'Ran Engineer',
       'Territory Development Representative (Tdr)', 'Telesales Agent',
       'Junior Software Developer', 'Sr. Manager It',
       'Software Developer', 'Internship', 'Senior Software Engineer',
       'Software Engineer', 'Frontend Developer', 'Brand Manager',
       'Data Analyst', 'Field Engineer', 'Territory Manager',
       'Customer Experience Representative', 'Finance Intern',
       'Office Administrator', 'Consultant', 'Software Engineer I',
       'Call Center Agent', 'Driver', 'Sales Associate',
       'Customer Service Representative (Csr)',
       'Consumer Business Intern', 'Systems Engineer',
       'Sales Representative', 'Global Management Trainee (Gmt)',
       'Cybersecurity Internship', 'Manager', 'Analyst',
       'Administrative Assistant', 'Assistant Project Manager',
       'Data Entry Clerk', 'Network Engineer', 'Cyber Security Analyst',
       'Audit Associate', 'Specialist', 'It Specialist',
       'Program Manager', 'Backend Engineer', 'Finance',
       'Data Analyst Intern', 'Integration Engineer', 'Sales Assistant',
       'Solutions Architect', 'Legal Intern', 'Sre/Devops Engineer',
       'Contractor', 'Agribusiness Manager', 'Ux Designer',
       'Data Analytics Partner', 'Trade Development Representative',
       'It Contractor', 'Software Developer Intern',
       'Senior Assurance Officer', 'Graduate Trainee', 'Web Developer',
       'Customercare Executive', 'Admin Intern', 'Account Executive',
       'Business Analyst', 'Customer Care Representative', 'Qa Engineer',
       'Data Analyst/Junior Data Scientist', 'Treasury Analyst',
       'Customer Success Manager', 'Engineer', 'It Manager',
       'Devops Engineer', 'Senior Data Analyst', 'Team Leader',
       'Ml Engineer', 'Sofatware Engineer', 'Manager, Financial Services',
       'Sales Executive', 'Human Resources Assistant',
       'Customer Experience Executive', 'Customer Service Agent',
       'Data Associate', 'Quality Engineer', 'Category Manager',
       'Computer Science/Engineering', 'Front End Developer',
       'Technology Intern', 'Finance Manager', 'Data Scientist',
       'Senior Service Reliability Engineer', 'Business Development',
       'Structural Engineer', 'Administrative', 'Management Trainee',
       'Site Reliability Engineer Intern', 'Cybersecurity Analyst',
       'Backend Developer', 'Software Engineer(Internship)',
       'Engineering Manager', 'Database Administrator', 'Accountant',
       'Agile Coach', 'Marketing Coordinator', 'Cybersecurity',
       'Vas Engineer', 'Ran Capacity Planning Engineer',
       'Accounts Payable', 'Principal Auditor', 'Commercial Manager',
       'Field Agent', 'Customer Care Specialist',
       'Senior Executive Assistant', 'Finance Team Lead',
       'Senior Integration Engineer',
       'Software Development Engineer In Test (Sdet)', 'Sales',
       'Android Developer', 'Graphic Designer', 'Account Manager',
       'Customer Support Specialist', 'Ip Support Engineer',
       'Full Stack Engineer', 'Data Engineer',
       'Çustomer Service Representative', 'Senior Solutions Architect',
       'Front Desk Agent', 'Telecom Engineer', 'Data Entry',
       'Call Center Representative', 'Technical Lead',
       'Lead Android Developer', 'Senior Cse', 'Telesales Representative',
       'Ftth (Fiber to the Home) Engineer',
       'Customer Service Account Associate', 'Anonymous Contractor',
       'Human Resources Manager', 'Senior Network Engineer',
       'Solutions Engineer', 'Casual Team Member', 'Technician',
       'Bi Developer', 'Network Administrator',
       'Senior Data Analytics Engineer', 'It Intern',
       'Middle Ios Developer', 'Client Relationship Executive',
       'Accounts Assistant', 'Systems Administrator',
       'Radio Access Network Engineer', 'It Assistant',
       'Software Engineer Intenship', 'Marketing Intern',
       'Product Manager', 'Senior Software Developer', 'It Technician',
       'Chef', 'Direct Sales Representative',
       'It Technical Support Specialist', 'Business Development Manager',
       'Marketing', 'Tdr Trade Development Representative',
       'Anonymous Employee', 'Band H', 'Program Director',
       'Enterprise Risk Management', 'Digital Marketing',
       'Accounts Receivable', 'Microservices Developer',
       'Product Designer', 'Financial Services Intern', 'Human Resources',
       'Human Resources Specialist (Hr Specialist)',
       'Machine Learning Engineer', 'Cloud Support Engineer',
       'Quality Assurance', 'Junior Data Analyst',
       'Senior Manager International Business', 'Janitor/Cleaner',
       'Software Engineer Intern', 'Technical Support Engineer',
       'Chief Technology Officer (Cto)', 'Principal',
       'Graduate Engineer Trainee', 'Support Analyst',
       'Market Researcher', 'Qaengineer', 'Enterprise Support Engineer',
       'Online Chat Agent', 'Sales Officer', 'Chat Moderator',
       'Principal Engineer', 'Software Development Engineer (Sde)',
       'Scrum Master/Agile Coach', 'Merchant Support', 'Intern Engineer',
       'Chief Executive Officer (Ceo)', 'Product Owner',
       'Big Data Engineer', 'Analysts', 'Is Intern', 'Ict Officer',
       'Customer Care Executive', 'Sales Manager', 'Security Guard',
       'Pricing Analyst', 'Accounts Clerk', 'Senior Graphic Designer',
       'Sales Represenative', 'Fixed Support Central Dispatch Engineer',
       'Sales Agent', 'Cloud Engineer', 'Software Engineer Ii',
       'Solution Architect', 'Computer Programmer', 'Soc Engineer',
       'Customer Experience Specialist', 'Customer Sevice Specialist',
       'Sales Intern', 'Analytics Manager', 'Financial Controller',
       'End User Support', 'Communications',
       'Financial Services Representative', 'Saler Support',
       'Frontend Web Developer', 'Category Sourcing Manager',
       'Head Of Technical', 'Sweeper', 'Treasury Intern',
       'Dealer Relationship Manager', 'Tech Leader', 'Hod',
       'Fullstack Developer', 'Network Intern', 'Integrations Engineer',
       'Paid Ads Specialist', 'Database Administrator (Dba)',
       'Social Media Manager', 'Tech Support Engineer',
       'Asm (Area Sales Manager)', 'Junior Software Engineer',
       'Communications Manager', 'Ict Manager',
       'Field Sales Representative', 'It Business Analyst',
       'Customer Care', 'Direct Sales Agent', 'Marketing Specialist',
       'It Support', 'Ui-Ux Designer & Graphics Designer',
       'Vas Support Engineer', 'Supervisor', 'Data Base Administrator',
       'Graduate Management Engineer', 'Software Engineering',
       'Senior Engineer', 'Business Data Analyst',
       'Discover-Graduate Program', 'Financial Analyst',
       'Head Of Research', 'Data Manager', 'Accounts Intern',
       'Senior Manager Enterprise Service Delivery',
       'Principal Radio Planning Engineer', 'Retail Analyst',
       'Mid Level Manager', 'Human Resources Officer',
       'Security Controller', 'Senior Manager - Retail Transformation',
       'Ipcc Engineer', 'Senior Management', 'Corporate Ressponsibility',
       'Procurement Intern', 'Training Coordinator',
       'Consulting Hardware Engineer', 'Sales Executives',
       'Technology Academy', 'Project Deployment',
       'Telecommunications Engineer', 'Management Engineer',
       'Core Network Engineer', 'Hrbp', 'Retail Cee',
       'Technical Project Manager', 'Territory Account Executive',
       'Enterprise Infrastructure', 'Quality Analyst',
       'Social Media Analyst', 'Customer Experience Manager',
       'Senior Manager', 'Sector Manager', 'Government Affairs Manager',
       'Support Lead', 'Retail Customer Experience Executive',
       'Anonymous Intern', 'Computer Science Student',
       'Data Science Intern', 'Information Security Analyst',
       'Senior Manager Innovation', 'Technology Analyst',
       'Senior Officer', 'Route Salesman', 'Junior Data Scientist',
       'Manager, Operations', 'Human Resources Consultant',
       'Bi Management', 'Integration Support Analyst',
       'Acting Inbound Logistics Manager',
       'Telecommunications (Oss) Engineer', 'Product Marketer',
       'Enterprise Provisioning', 'Principal Operations Officer',
       'Retail Assistant - Customer Services', 'Women In Technology',
       'Sales And Marketing', 'Engineering Internship',
       'Senior Devops Engineer',
       'Principal Human Resource Business Partner (Hrbp) Officer',
       'Regional Sales Manager', 'Segments Manager', 'Office Assistant',
       'Platinum Support Manager', 'Business Development Associate',
       'Principal Internal Auditor', 'Dealer Manager',
       'Softeware Engineer', 'Quality Assurance Analyst', 'Hr-Intern',
       'Corporate Sales', 'Logistics Quality Assurance',
       'It Support Analyst', 'Bi Analyst', 'Relationship Manager',
       'Call Centre Team Leader', 'Territory Account Manager',
       'Senior Manager Operations Engineering', 'Systems Analyst',
       'Principal Analyst', 'Call Center Customer Service Representative',
       'Customer Service Associate', 'Finance Professional',
       'Senior Officer, Supplier Qualification And Contracts Management',
       'Products Development Engineer', 'Supply Chain',
       'User Experience Designer', 'Chief Executive Officer',
       'Ip Planning Engineer', 'Software Development Intern',
       'Intraoperative Neuromonitoring Tech', 'Tdr', 'Stock Controller',
       'Coder', 'Configuration And Support Engineer',
       'Inventory Controller', 'Nairobi', 'Customer Executive Officer',
       'Graduate Electrical Engineer', 'Projects Officer',
       'Cloud Solutions Engineer', 'Senior Iot Engineer',
       'Personal Assistant', 'Digital Customer Experience Manager',
       'Qa Governance & Operations', 'Applications Support Engineer',
       'Intern - Hourly', 'Kenya – Republic Of Kenya',
       'Technical Consultant', 'Digital Product Manager',
       'Provisioning Engineer', 'Assistant Store Manager',
       'Software Engineer - Android', 'Tdr - Sales', 'Fibre Technician',
       'Senior Scrum Master', 'Ass Treasurer', 'Compliance Manager',
       'Senior Customer Service Representative',
       'Talent Acquisition Specialist',
       'Capital Projects Business Partner', 'Operations Team Leader',
       'Network Officer', 'Procurement Analyst', 'Networking Engineer',
       'Business Executive', 'Secretary', 'Radio Planning Engineer',
       'Financial Advisor', 'Ran', 'Product Development',
       'National Account Manager', 'Computer Systems Engineer',
       'Senior Human Resources Officer', 'Retention Manager',
       'Programme Analyst', 'Senior Principal Developer',
       'Procurement Officer', 'Operations Engineer', 'Staff Accountant',
       'Senior Product Manager', 'Enterprise Service Desk Engineer',
       'Retail Quality Analyst', 'Remote Support Engineer',
       'Customer Service Specialist', 'Talent Acquisition Intern',
       'Assistant Commercial Manager', 'It Incident Management Analyst',
       'Data Analyst/Data Scientist', 'Senior Tech Lead',
       'Student Intern', 'Junior Graphic Designer',
       'Ran Optimization And Planning Engineer',
       'Commercial Sales Consultant', 'Senior Accountant',
       'Service Assurance Engineer', 'Digital Experience Executive',
       'Cyber Security Consultant', 'Call Centre Agent',
       'Devops/Full-Stack Developer', 'Marketer', 'Ip Engineer',
       'Advertising Sales Or Data Entry', 'Technical Enterprise Services',
       'Senior Sourcing Engineer', 'Ict', 'Anonymous Temporary Employee',
       'Contact Center Team Leader', 'Digital Media Executive',
       'Technology', 'Risk Management', 'Project Management Intern',
       'Social Worker', 'Customer Support', 'Site Administrator',
       'Qa Intern', 'Software Quality Assurance Engineer',
       'Sales Manager Cee', 'Writer', 'Territory Sales Representative',
       'Network Planning Engineer', 'Business Engagement Manager',
       'Lead Engineer', 'Senior Communications Manager',
       'Enterprise Quality Assurance Analyst', 'Typing',
       'Resource Planning Analyst', 'Content Marketer', 'Cyber Security',
       'It Solutions Architect', 'Stock Control',
       'Computer Scientist (1550)', 'Field Service Engineer',
       'Manager - New Business Development', 'Cleaning',
       'Django Developer', 'Executive Assistant', 'Inventory Accountant',
       'Finance/Accounting', 'Delear Sales Associate',
       'Systems Developer', 'Noc Engineer', 'Product Development Manager',
       'Research Associate', 'Online Data Entry', 'Brand Promotion',
       'Actuarial Analyst', 'Legal Assistant', 'Designer',
       'Stocks Controller', 'Core Network Support',
       'Intern For Financial Services', 'Customer Service Executive',
       'I T Analyst', 'Senior Software Engineer/Tech Lead',
       'Mobile Developer', 'Internal Auditor',
       'Financial Service Operator', 'Senior Financial Services Officer',
       'Customer Support Representative',
       'Regional Business Development Manager',
       'Sales, Marketing And Communications Professional', 'Mpesa',
       'Senior Lawyer', 'Operations Manager', 'Relationship Officer',
       'Retail Centre Team Leader', 'Executive', 'Itspecialist',
       'Brand Experience Activations Manager', 'Full Stack Developer',
       'Network Optimization Engineer', 'Information Technology',
       'Legal Officer', 'Telecommunications Engineering Specialist',
       'Senior Ux Designer'], dtype=object)

In [110]:
# rename detail
SafRev["Job Title"].replace({"I T Analyst":"IT Analyst"}, inplace=True)

In [ ]:
# SafRev["Job Title"].replace({"Tdr Trade Development Representative":"(Tdr) Trade Development Representative"}, inplace=True)
# SafRev["Job Title"].replace({"Qaengineer":"Qa Engineer"}, inplace=True)
# SafRev["Job Title"].replace({"Çustomer Service Representative":"Customer Service Representative"}, inplace=True)
# SafRev["Job Title"].replace({"Sofatware Engineer":"Software Engineer"}, inplace=True)
# SafRev["Job Title"].replace({"Softeware Enginee":"Software Engineer"}, inplace=True)
# SafRev["Job Title"].replace({"Ftth Engineer":"Ftth (Fiber to the Home) Engineer"}, inplace=True)
# SafRev["Job Title"].replace({"Software qa engineer":"Software Qa Engineer"}, inplace=True)
# SafRev["Job Title"].replace({"Tdr":"Trade Development Representative"}, inplace=True)
# SafRev["Job Title"].replace({"Itspecialist":"IT Specialist"}, inplace=True)
# SafRev["Job Title"].replace({"KEY NOT FOUND: jobLine.seasonal-current":"(Job) seasonal_current"}, inplace=True)
# SafRev["Job Title"].replace({"I T Analyst":"IT Analyst"}, inplace=True)

In [67]:
# locating value on the dataset
SafRev[SafRev["Job Title"]=="Ftth (Fiber to the Home) Engineer"]

,Job Title,Job Rating,Time,Job Status,Pros,Cons
288,Ftth (Fiber to the Home) Engineer,4.0,2024-06-07,"Current employee, more than 1 year",There are very many Opportunities,A lot of work pressure and demand

In [64]:
# changing the headers on the file into headers
SafRev["Job Title"] = SafRev["Job Title"].str.title()

In [75]:
# locating specific data
SafRev.query('`Job Title`=="Anonymous Contractor"')

,Job Title,Job Rating,Time,Job Status,Pros,Cons
291,Anonymous Contractor,4.0,2024-05-29,"Former contractor, more than 3 years",Diversity and inclusion\nGood salary and compe...,Too much sales pressure to meet monthly sales ...
340,Anonymous Contractor,5.0,2024-04-12,"Current contractor, less than 1 year",comradarie and collaboration. also exposure.,working hours. not enough pay.
377,Anonymous Contractor,2.0,2024-03-13,"Current contractor, more than 5 years",-can be remote\n-Good benefits,-Bad team leaders\n-Bad for mental health\n-Ba...
875,Anonymous Contractor,5.0,2019-02-17,"Current contractor, more than 3 years",Its a place one can admire to work at,It always values work life balance thus being ...
951,Anonymous Contractor,4.0,2022-06-07,"Former contractor, less than 1 year",Great & flexible work environment,Some work activities can be lengthy due to pol...
1063,Anonymous Contractor,4.0,2017-10-24,"Former contractor, more than 1 year",Great opportunity & blue chip firm to learn,High pressure work that deserves full commitme...
1184,Anonymous Contractor,3.0,2021-09-07,Current contractor,best place to work in kenya,lower salary compared to what is expected
1212,Anonymous Contractor,4.0,2019-08-14,"Current contractor, more than 1 year",Annual bonus and competitive salary,None so far but could do better
1278,Anonymous Contractor,5.0,2022-09-02,"Current contractor, less than 1 year",Many career opportunities\nConducive environment,Hired through agency so you get less salary

In [88]:
SafRev['Job Status'].unique()

array(['Former employee, more than 1 year',
       'Current contractor, more than 1 year',
       'Former employee, more than 3 years', 'Former employee',
       'Former intern, less than 1 year',
       'Former contractor, more than 3 years', 'Current employee',
       'Current employee, more than 1 year',
       'Former contractor, more than 1 year',
       'Current contractor, more than 3 years',
       'Current employee, less than 1 year', 'Former intern',
       'Current contractor', 'Current employee, more than 3 years',
       'Former employee, more than 10 years', 'Former contractor',
       'Current employee, more than 5 years',
       'Current employee, more than 10 years',
       'Current temporary employee', 'Former employee, more than 8 years',
       'Current intern, more than 1 year',
       'Former employee, less than 1 year',
       'Former employee, more than 5 years',
       'Former freelancer, less than 1 year', 'Current intern',
       'Former temporary employee, less than 1 year',
       'Current intern, less than 1 year', 'Former temporary employee',
       'Current employee, more than 8 years',
       'Former contractor, less than 1 year',
       'Current contractor, more than 8 years',
       'Current contractor, less than 1 year', 'Current freelancer',
       'Current contractor, more than 5 years',
       'Former intern, more than 1 year',
       'Former freelancer, more than 1 year',
       'Current freelancer, more than 1 year',
       'Former contractor, more than 5 years', 'Formerly self-employed',
       'Former intern, more than 3 years',
       'Former temporary employee, more than 3 years',
       'Current freelancer, less than 1 year',
       'Former contractor, more than 8 years', 'Currently self-employed',
       'Current temporary employee, more than 3 years',
       'Former freelancer', 'KEY NOT FOUND: jobLine.seasonal-current',
       'KEY NOT FOUND: jobLine.seasonal-former'], dtype=object)

In [86]:
SafRev[SafRev['Job Status']=="Former freelancer"]

,Job Title,Job Rating,Time,Job Status,Pros,Cons
1262,Computer Scientist (1550),3.0,2021-12-17,Former freelancer,paid relatively well compared to other companies,jobs did not come oftenly
1366,"Sales, Marketing And Communications Professional",4.0,2020-11-19,Former freelancer,Good and well structured organization,Takes time to absorb its employees

In [117]:
pd.set_option('Display.Max_rows',None)
pd.set_option('Display.Max_columns',None)
SafRev[["Pros"]]

                                                   Pros
0     Flexible hours, supportive team, good training...
1     Great for gaining experience on large scale en...
2     Strong support for professional growth through...
3                       the working experience was good
4              Great work environment. Regular bonuses.
5                       RTO policy 3 days in the office
6     Opportunities for growth\nGood company \nGreat...
7               Good place to work and grow career-wise
8                      Job security\nBonus is available
9       Conducive work environment for employees growth
10           Salaries paid on time\nFamiliar route plan
11                 Good work environment and aesthetics
12    Safaricom really cares about her employees' we...
13    Good work-life balance and supportive team env...
14    As an employer, offers significant advantages ...
15    I really don't have any pros for them. Hasn't ...
16                          you Offer the best services
17    They try to help interns and the managers are ...
18    Learning and skill building on enterprise leve...
19                        to be updated at a later time
20           Salaries paid on time\nFamiliar route plan
21                 Good work environment and aesthetics
22    Safaricom really cares about her employees' we...
23    Good work-life balance and supportive team env...
24    As an employer, offers significant advantages ...
25    I really don't have any pros for them. Hasn't ...
26                          you Offer the best services
27    They try to help interns and the managers are ...
28    Learning and skill building on enterprise leve...
29                        to be updated at a later time
30           Salaries paid on time\nFamiliar route plan
31                 Good work environment and aesthetics
32    Safaricom really cares about her employees' we...
33    Good work-life balance and supportive team env...
34    As an employer, offers significant advantages ...
35    I really don't have any pros for them. Hasn't ...
36                          you Offer the best services
37    They try to help interns and the managers are ...
38    Learning and skill building on enterprise leve...
39                        to be updated at a later time
40                - Heard some horror stories recently.
41                      decent salary but can do better
42    - Very friendly and easy to work with colleagu...
43       Good environment to learn and grow ones career
44                  Very educative and gives experience
45    Exposure to different network technologies, pe...
46    Reputable Organization\nGreat compensation\nGr...
47    There is good medical cover, and they allow yo...
48           Great company culture. \nGood health cover
49    Hybrid working. \nAmazing work culture. \nLots...
50    Good starting salary in Kenya.\nGood benefits ...
51    Best working conditions,provided transport.goo...
52    good working environment sometimes and management
53    Good learning Experience and opportunities to ...
54               huge operational budget for innovation
55    They have a good work culture and the working ...
56                       Good renumeration as an intern
57                         to have a better high salary
58       Good salary, professional working environment.
59                    Great packs and flexible schedule
60                    Opportunities for growth are many
61             Good learning mechanisms and work ethics
62    Great work life balance\nHybrid working\nLovel...
63             Good compensation and great work culture
64    Great working environment with huge salary ben...
65    Learning opportunities are provided for person...
66    Structured Program: Clear orientation and a we...
67              Good pay\nAirtime and insurance benefit
68          Good Corporate Exposure and Staff Benefits.
69    Work from home\nGood bonus\nMedical cover\nMoU...
70                     Great benefits for the employees
71    - Great working culture with many opportunitie...
72                        A good side hustle for youth.
73             Good employee benefits; health, fuel etc
74                     Good employer in terms of reward
75                   Great place to work at\n Recommend
76               Opportunities to work in various roles
77    There is flexibility of doing remote work. Guy...
78    allows for innovative thinking and out of box ...
79             they really take care of their employees
80             Good Pay and favorable work environment.
81                     all time best employer in kenya.
82    Very good working environment with full medica...
83    a competitive salary and benefits package, opp...
84        Competitive salary and good work environment.
85                          I love working at safaricom
86    easy access to the office as it is located in ...
87                       A stable company with good pay
88           Bonuses are many\nGood working environment
89                profitable, great benefits and secure
90                    benefits are plenty for employees
91               Bonuses are almost guaranteed annually
92                             ok working here but busy
93    Great employee benefits\nGood working environm...
94              in doing finance job at safaricom kenya
95    Networking\nTravel\nEnvironment \nSkills\nExpe...
96                   Good opportunity to grow and leaen
97            Good work environment and team management
98    A workplace that truly prioritizes innovation,...
99                  It's good. I enjoyed my time there.
100    friendly workmates and sound in creating rapport
101                    A nice working environment to be
102             Learn alot due to their  large ecosytem
103         friendly work space in the work environment
104   Innovative Work Environment: Opportunities to ...
105   Handson experience\nIntroduction to vast conce...
106                  I loved it and hope for retainment
107                         very good team at safaricom
108                         It is a good starting point
109                   it has a good working environment
110          Diverse work culture and good compensation
111                          Great to work with and csr
112                           Awesome to work within it
113                               A lot of team playing
114   I had the best work experience at Safaricom. S...
115                   great benefits such as healthcare
116              Good bonuses\nGood working environment
117                    The working hours are reasonable
118                         It offers the best training
119   Hospitable and supportive in career and person...
120                  Good working environment all round
121   Inclusivity, empowering, good learning opportu...
122   Excellent working culture with a flat leadersh...
123                              You get to learn a lot
124          Good and hefty worker salary renumerations
125                           Really good place to work
126   Good salary and benefits, limited opportunitie...
127     Good working environment with great ventilation
128                 Nice working environment in Nairobi
129           Over the years, the quality has been okay
130   At Safaricom we are driven by our spirit of pu...
131                      Great work happening there now
132              Career growth opprotunity is available
133   As a person new in the industry, the environme...
134              Great career growth\nIdeal compesation
135   Good working environment. Pay for club membership
136     Good salary.. learning opportunities and growth
137          Timely delivery and customer satisfaction.
138                       Great work culture at company
139                   timely pay good working condition
140                     Good Working hours can be great
141      Great working environment and a chance to grow
142             It gives you a chance for career growth
143                      They take their work seriously
144        There is such a great work-life balance here
145                 Amazing place to work,10/10 culture
146             Great salary provided. Bonus available.
147   The company is great and provides rooms for gr...
148   * It offers a good work-life balance, WFH.\n* ...
149                  Good employer with great benefits.
150     Fast paced, great opportunity to learn and grow
151   Good work life balance for engineers except gu...
152   Amazing employer with conducive environment to...
153     Benefitial in terms of work and life experience
154   Good managers, flexible work. No micro-managem...
155   If you want to grow from a capacity perspectiv...
156   Work-life balance and employee well-being is e...
157   Good work life balance\nOvertime is paid when ...
158   Comfortable working hours \nExposure \nTime ma...
159            It's a condusive environment to work in.
160   Good working environment\nDays off, sick leave...
161                                it was nice and good
162           Friendly work environment with good peope
163       Good work-life balance with the hybrid setup.
164   amazing and helpful. Has enabled me to gain a ...
165        Growth, networking, Had a supportive manager
166   Most teams are Hybrid \nGood pay compared to p...
167   Structured Environment: Offers a stable and or...
168                       Good location. HQ in Nairobi.
169               Good environment. Good leadership etc
170        Great culture, Amazing perks and team spirit
171   Good opportunity for growth and career acceler...
172                            good company to work for
173             Exposure\nGood pay\nFriendship \nGrowth
174                                learn and grow a lot
175           Good benefits, insurance, travel, airtime
176   The QA team is well organised and supported. T...
177      Good working environment good medical benefits
178   Good experience in interacting with various cl...
179   It is great when you are not working on a time...
180   Medical, Pay, Learning opportunities and exposure
181          Good compensation. Prompt payment are made
182                   Best in terms of salary,and skils
183   You interact and learn from lot's of smart peo...
184              Passionate about sales in the company.
185   - Employee benefits like medical insurance, ai...
186               Great employer with a young workforce
187                           you learn a lot of things
188                                 they have a gym bro
189       Flexible. Remote option, Learning environment
190           Good working surrounding and environment.
191   Very self growth condusive environment.\nGood ...
192   30 vacation days a year.\nGreat professional d...
193               money money money, more money ...food
194                It is a place that values diversity.
195   Exposure to a large and growing market: Safari...
196    Very mature company with well defined processes.
197   Good pay, Good benefits, National Esteem. Reso...
198   Good salary\nFlexible working hours\nCaree growth
199   Free lunch\nGood pay\nGreat staff\nGood manage...
200                        Great very much to be honest
201                     Work environment is fairly okay
202                 Good perks. Good brand recognition.
203           Good benefits, security, teamwork is okay
204    Comfortable, great integration and accommodating
205    Great place for beginners to start their careers
206                Good opportunity and maybe retaining
207               Learning opportunities are a lot here
208   You have freedom to design solutions. Compared...
209            Great benefits perks, Salary, and Bonus.
210                      Good benefits and pay packages
211   best life balance and good salary renumeration...
212                          learn a lot within the org
213   Competitive remuneration\nNo dull day, differe...
214          Connection as you interact with many teams
215         Insurance\nFlexible hours\nGood team spirit
216                   They have a good working culture.
217         Its a good company witg healthy environment
218        Great working environment, with minimum fuss
219                Good working conditions for everyone
220            Manageable working pressure within teams
221   The Medical cover is so good.\nSecurity of the...
222   Good insurance\nFlexible working schedule\nOve...
223            Great working here it is an awesome plae
224   - Working in tech\n- Opportunities for growth\...
225   1. Great exposure for someone new to the corpo...
226   A good working environment , had a good time t...
227                 Good managers with clear objectives
228                          best in the world you know
229                good work life balance for employees
230   awesome working environment to gain profession...
231                        Team work and flexible hours
232                  Teamwork\nA Billion dollar company
233     Its a good company to give exposure to employer
234                        Good pay, big company status
235                great for career growth and exposure
236                              You can work from home
237   Opportunities for growth.\nMultifaceted approa...
238           A lot of Flexibility in working locations
239                      It is flexible and pay is good
240   Shift based, flexible and has work from home o...
241       Timely remuneration with benefits and bonuses
242   Engineering problems top-notch coz of large cu...
243                          Best working culture in KE
244   You get good exposure\nGood work ethic\nGood b...
245         Exposure to learning tools and technologies
246   Insurance \nJob security\nBig company \nGood r...
247              Good working environment for employees
248   - Decent compensation and benefits including a...
249            Great collaboration, Honesty and agility
250   Flexible working working hours, opportunity fo...
251                Amazing work environment and people.
252   The work environment is pleasant.\nThe culture...
253   Awesome benefits in terms of health insurance ...
254   Popular company \nGreat salary\nGood work envi...
255               Good working environment and good pay
256                 Life work balance ang great culture
257                   Proper job scale and remuneration
258     No micromanagement. Helps its employees to grow
259                office perks;free stuff as an intern
260   Great Perks\nAwesome Staff\nRevolutionary lead...
261          Satisfied with the workplace and the team.
262                   it has a good working environment
263                       Good place to work for growth
264                     Great exposure for skill growth
265                          Saf is an amazing employee
266                         flexible fun good pay bonus
267                         It is a great place to work
268   Flexible Accommodative lots of learning opport...
269   Great benefits and overall tech industry exposure
270       Good environment for learning and development
271    Competitive salary with opportunities for growth
272   Great corporate support in both physical and m...
273   Loved it there. Very good employee-boss relati...
274                    Nice\nGreat\nBest\nAwesome\nGood
275   Improved learning and development aslo Provide...
276          awesome\nfair\njust\nsupportive\ninclusive
277   Amazing team and culture. Good vision and mission
278             Salaries arrive in time, work from home
279           Overtime, bonus , leaves , work from home
280   One of the safest place to work in. Best time ...
281   Job Security\nRemote working\nNo Micro managem...
282                          This si a goood co to work
283           Great pay and flexible working conditions
284                          Fairly Good place to work.
285                     They value employees \nGood pay
286      Great place to work but it needs alot of focus
287          Best work life balance, Hybrid work hours.
288                   There are very many Opportunities
289   Flexible working environment. Hybrid works for me
290                    the company offers good benefits
291   Diversity and inclusion\nGood salary and compe...
292   Quite easy to climb up the ladder financially ...
293                    Good culture\nGreat manager\nWFH
294             good for career growth if you work hard
295   Best working environment, workstations very OK...
296        Great place to work. Professional practices.
297                       Great place to work and learn
298   good salary, good working envirnment, lots of ...
299   Flexibility, Good compensation, work life balance
300            Great work environment\nGreat incentives
301                  They offer the best staff service.
302                         I love the hybrid structure
303   Great culture and benefits with opportunities ...
304   Great environment \nMedical Insurances \nPensi...
305   Career growth due to upskilling and alot of op...
306                             none, all is good. none
307                           Best company to work for.
308               Great Benefits\nGood work environment
309   Great work experience and networking opportuni...
310                      i had no downsides while there
311   Considerate earnings\nGood working environment...
312        Safaricom remains the best employer in Kenya
313               good work culture\nagile\ncompetitive
314              Wonderful offices\nSalary paid on time
315       Good working Conditions, Interesting projects
316   Good enough to get exposure on working with la...
317   1. Although the work is challenging, it provid...
318    Flexibility\nHybrid\nRespect\nBenefits\nExposure
319                        Great environment to work in
320                           It's a great place to be.
321              Good benefit package for all employees
322                             Great team to work with
323   great employer\nWell Being health wise well ta...
324   Better renumeration and very good working envi...
325    Good place to work in.Great corporate experience
326   A lot of employee to employee support. Each em...
327                Awesome place to develop your skills
328   Career Development:\nLarge companies like Safa...
329   The exposure is great. You get to learn a whol...
330                        Great environment to work in
331             Gives you more experience and knowledge
332           Good management and employees are valued.
333              Flexi-working hours for it's employees
334                 Good benefits and customer focussed
335       The employee relations program are fantastic.
336   Networking with different professionals in the...
337     Nice company to work and good work life balance
338   The pay is okay, but it could be better. Takes...
339   Good benefits(medical cover, gym, etc) and fle...
340        comradarie and collaboration. also exposure.
341         The company offers Competitive compensation
342          Competitive salary for fulltime employees.
343                    great work life balance as a dev
344                        Good enevironment to work in
345   I completely love being at Safaricom. From the...
346   work from home\nyou are paid 2k per day when y...
347                           Work from home.\nGood pay
348                        I loved the learning process
349         good working environment great remuneration
350   The management team at our shop is very profes...
351   Shaped my career and really set me up for success
352   Good renumeration\nwork-life balance\nskills d...
353             Good technology and learning experience
354   It's an amazing place to start a career in tec...
355   Budding software engineering methodology. Expo...

In [118]:
SafRev.iloc[40]

Job Title                                Internship
Job Rating                                      2.0
Time                            2025-06-19 00:00:00
Job Status                            Former intern
Pros          - Heard some horror stories recently.
Cons            Heard some horror stories recently.
Name: 40, dtype: object

In [ ]:
pd.set_option('Display.Max_rows',None)
SafRev[["Pros", "Cons"]]