In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/Automating-Boring-Stuff-with-Python/Safaricom reviews/SafaricomReviews.csv")
data

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Brand ambassador,5.0,"Aug 8, 2025","Former employee, more than 1 year","Flexible hours, supportive team, good training...","Inconsistent hours, limited career growth, com..."
1,Senior mobile developer,4.0,"Jul 28, 2025","Current contractor, more than 1 year",Great for gaining experience on large scale en...,A lot of shifting priorities
2,Project manager,4.0,"Jul 15, 2025","Former employee, more than 3 years",Strong support for professional growth through...,Occasional tight deadlines and high-pressure t...
3,Ict technician,5.0,"Jul 18, 2025",Former employee,the working experience was good,there are no major drawbacks i can talk about
4,Intern,5.0,"Jul 15, 2025","Former intern, less than 1 year",Great work environment. Regular bonuses.,None I can think of
...,...,...,...,...,...,...
1405,Anonymous employee,3.0,"Mar 7, 2022","Current employee, more than 1 year",A good place to work,Being overworked and under high pressure
1406,Intern,4.0,"Apr 8, 2022","Former intern, less than 1 year",Good Benefits and Minimal Workload.,Poor structure for internship programme.
1407,Internship,5.0,"Jun 13, 2022",Current intern,Good experience working at safaricom,Could pay interns better atleast
1408,Senior ux designer,2.0,"Jun 20, 2022",Former employee,Good work place to work in Kenya,No cons here in kenya
1409,Intern,5.0,"Aug 16, 2022",Current intern,Good Salary for an intern,none that I came across

In [24]:
# EDA on the data
def display(x):
    print("==============================")
    print(x.columns)
    print()
    print("Returns the data information")
    print("==============================")
    print(x.info)
    print()
    print("Returns the information in more details")
    print("==============================")
    print(x.describe())
    print()
    print("The data type")
    print("==============================")
    print(x.dtypes)
    print()
    print("The number of null values in the dataset")
    print("==============================")
    print(x.isna().sum())
display(data)

==============================
Index(['Job Title', 'Job Ratings', 'time', 'JobStatus', 'Pros', 'Cons'], dtype='object')

Returns the data information
==============================
<bound method DataFrame.info of                     Job Title  Job Ratings          time  \
0            Brand ambassador          5.0   Aug 8, 2025
1     Senior mobile developer          4.0  Jul 28, 2025
2             Project manager          4.0  Jul 15, 2025
3              Ict technician          5.0  Jul 18, 2025
4                      Intern          5.0  Jul 15, 2025
...                       ...          ...           ...
1405       Anonymous employee          3.0   Mar 7, 2022
1406                   Intern          4.0   Apr 8, 2022
1407               Internship          5.0  Jun 13, 2022
1408       Senior ux designer          2.0  Jun 20, 2022
1409                   Intern          5.0  Aug 16, 2022

                                 JobStatus  \
0        Former employee, more than 1 year
1     Current contractor, more than 1 year
2       Former employee, more than 3 years
3                          Former employee
4          Former intern, less than 1 year
...                                    ...
1405    Current employee, more than 1 year
1406       Former intern, less than 1 year
1407                        Current intern
1408                       Former employee
1409                        Current intern

                                                   Pros  \
0     Flexible hours, supportive team, good training...
1     Great for gaining experience on large scale en...
2     Strong support for professional growth through...
3                       the working experience was good
4              Great work environment. Regular bonuses.
...                                                 ...
1405                               A good place to work
1406                Good Benefits and Minimal Workload.
1407               Good experience working at safaricom
1408                   Good work place to work in Kenya
1409                          Good Salary for an intern

                                                   Cons
0     Inconsistent hours, limited career growth, com...
1                          A lot of shifting priorities
2     Occasional tight deadlines and high-pressure t...
3         there are no major drawbacks i can talk about
4                                   None I can think of
...                                                 ...
1405           Being overworked and under high pressure
1406           Poor structure for internship programme.
1407                   Could pay interns better atleast
1408                              No cons here in kenya
1409                            none that I came across

[1410 rows x 6 columns]>

Returns the information in more details
==============================
       Job Ratings
count  1410.000000
mean      4.238298
std       0.861581
min       1.000000
25%       4.000000
50%       4.000000
75%       5.000000
max       5.000000

The data type
==============================
Job Title       object
Job Ratings    float64
time            object
JobStatus       object
Pros            object
Cons            object
dtype: object

The number of null values in the dataset
==============================
Job Title      0
Job Ratings    0
time           0
JobStatus      0
Pros           0
Cons           0
dtype: int64

In [7]:
# printing the first 20 elements on the dataset
data.head(20)

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Brand ambassador,5.0,"Aug 8, 2025","Former employee, more than 1 year","Flexible hours, supportive team, good training...","Inconsistent hours, limited career growth, com..."
1,Senior mobile developer,4.0,"Jul 28, 2025","Current contractor, more than 1 year",Great for gaining experience on large scale en...,A lot of shifting priorities
2,Project manager,4.0,"Jul 15, 2025","Former employee, more than 3 years",Strong support for professional growth through...,Occasional tight deadlines and high-pressure t...
3,Ict technician,5.0,"Jul 18, 2025",Former employee,the working experience was good,there are no major drawbacks i can talk about
4,Intern,5.0,"Jul 15, 2025","Former intern, less than 1 year",Great work environment. Regular bonuses.,None I can think of
5,Site reliability engineer,4.0,"Jul 14, 2025","Current contractor, more than 1 year",RTO policy 3 days in the office,Workload may be too much sometime
6,Software qa engineer,3.0,"Jul 13, 2025","Former contractor, more than 3 years",Opportunities for growth\nGood company \nGreat...,Tough management \nExtreme work conditions (pr...
7,Customer service,4.0,"Jul 8, 2025","Former intern, less than 1 year",Good place to work and grow career-wise,Is place that offers carrier growth
8,Customer service representative,3.0,"Jul 3, 2025",Current employee,Job security\nBonus is available,No growth\nCompensation for customer care is n...
9,Ran engineer,4.0,"Jul 6, 2025",Former employee,Conducive work environment for employees growth,Have to meet strict deadlines
10,Territory development representative (tdr),4.0,"Jun 28, 2025","Current employee, more than 1 year",Salaries paid on time\nFamiliar route plan,Working via agency\nNo room for growth
11,Telesales agent,5.0,"Jun 26, 2025",Former employee,Good work environment and aesthetics,Corporate work pressure and politics
12,Customer service representative,4.0,"May 25, 2025","Former contractor, more than 1 year",Safaricom really cares about her employees' we...,How I wish they could intervene in the pay and...
13,Junior software developer,5.0,"Jun 7, 2025",Former employee,Good work-life balance and supportive team env...,Limited advancement opportunities and outdated...
14,Sr. manager it,5.0,"Jun 5, 2025",Former employee,"As an employer, offers significant advantages ...","High-pressure, competitive, and sometimes bure..."
15,Software developer,2.0,"Jun 18, 2025","Current contractor, more than 3 years",I really don't have any pros for them. Hasn't ...,no work life balance.\nscalling is almost impo...
16,Ict technician,4.0,"Jun 20, 2025","Current employee, less than 1 year",you Offer the best services,there are No cons about your performance
17,Intern,5.0,"Jun 5, 2025","Former intern, less than 1 year",They try to help interns and the managers are ...,It requires to put a lot effort and sometimes ...
18,Internship,5.0,"Jun 16, 2025",Former intern,Learning and skill building on enterprise leve...,None that I noticed. Good working place.
19,Senior software engineer,5.0,"Jun 11, 2025",Current contractor,to be updated at a later time,none i can think of right now

In [8]:
# printing the last 20 elements on the dataset
data.tail(20)

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
1390,Customer experience executive,5.0,"Oct 20, 2019","Current employee, more than 8 years",Safaricom PLC is a great employer,Career growth is limited
1391,Software engineer,3.0,"Feb 25, 2020","Former contractor, more than 3 years","Average Pay, Nice Projects, Highly engaging","Excess Work hours, Tight Deadlines"
1392,Product manager,5.0,"Oct 30, 2020","Former employee, more than 3 years","Good employer, great environment. Good","Pressure , though performance based"
1393,Engineer,4.0,"Dec 9, 2020","Current employee, more than 1 year",Great team to work with.,High pressure to meet deadlines
1394,Full stack developer,3.0,"Dec 15, 2020",Former employee,nice working with safaricom man,lots of mistakes from them ni wezi
1395,Software engineer,4.0,"Dec 26, 2020","Current employee, more than 3 years",Wonderful place to work as usual,No comment on the issue
1396,Network optimization engineer,5.0,"Feb 3, 2021",Current employee,Very good terms of employment,Slow career growth in technology
1397,Customer experience executive,5.0,"Feb 22, 2021","Former employee, more than 5 years",Good compensation. Diversity and Inclusion,Limited growth within 5 years
1398,Customer experience representative,2.0,"Mar 11, 2021",Former contractor,Company name is the only big thing,"No exposure,to contracted stuff controlling boss"
1399,Information technology,3.0,"Apr 14, 2021",Former temporary employee,efficient in communication sector in Kenya,luring customers to buy their bundles
1400,Legal officer,3.0,"May 13, 2021","Current employee, more than 5 years","Good salary, environment, benefits, offices ar...","Bad bosses, no career advancement"
1401,Telecommunications engineering specialist,4.0,"Jun 13, 2021","Current contractor, more than 8 years",Excellent company to be in,A lot tasks are in place
1402,Customer care representative,2.0,"Jun 19, 2021",KEY NOT FOUND: jobLine.seasonal-former,good company very efficient and fast,poor wadges and late payment rates
1403,Sales representative,5.0,"Oct 4, 2021",Current contractor,Effective communication\r\nTeam work\r\nCoachi...,Growth opportunities are not clear
1404,Account manager,4.0,"Jan 26, 2022",Current employee,Safaricom has good medical benefits,Safaricom Hr processes are very bureacratic
1405,Anonymous employee,3.0,"Mar 7, 2022","Current employee, more than 1 year",A good place to work,Being overworked and under high pressure
1406,Intern,4.0,"Apr 8, 2022","Former intern, less than 1 year",Good Benefits and Minimal Workload.,Poor structure for internship programme.
1407,Internship,5.0,"Jun 13, 2022",Current intern,Good experience working at safaricom,Could pay interns better atleast
1408,Senior ux designer,2.0,"Jun 20, 2022",Former employee,Good work place to work in Kenya,No cons here in kenya
1409,Intern,5.0,"Aug 16, 2022",Current intern,Good Salary for an intern,none that I came across

In [9]:
# printing the random sample of 20 elements
data.sample(20)

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
932,Customer care representative,3.0,"Nov 24, 2020","Current employee, less than 1 year",Comfortable pay with benefits with pick up to ...,No job security for the employees especially c...
844,Anonymous employee,5.0,"Sep 21, 2016","Current employee, more than 3 years",Offers a good learning and growth opportunity.,The management of the Human resource / old emp...
21,Telesales agent,5.0,"Jun 26, 2025",Former employee,Good work environment and aesthetics,Corporate work pressure and politics
1176,Software developer,5.0,"May 20, 2021",Current intern,The Organizational Culture is good and support...,Takes Long time to process requests
1393,Engineer,4.0,"Dec 9, 2020","Current employee, more than 1 year",Great team to work with.,High pressure to meet deadlines
428,Anonymous employee,5.0,"Jan 6, 2024","Current employee, more than 1 year",great work environment.\nopportunity for growt...,mixed up schedule in regards to time
1018,Category sourcing manager,5.0,"Sep 3, 2021",Current employee,Great company that lives to its true purpose o...,None that I can think of at this time
524,Software engineer,5.0,"Aug 17, 2023",Former employee,"Good place to work for, good people",There is none to give at the moment
1368,Sales agent,4.0,"Mar 19, 2021",Former contractor,Friendly environment to work and grow,Too much Pressure from the employers
457,Market researcher,4.0,"Nov 30, 2023",Current employee,The Best employer in Kenya,Bad work culture and environment
522,Principal engineer,4.0,"Aug 24, 2023","Current employee, more than 5 years","Bonus, medical, airtime allowance, transport a...",Salary review is poor Growth is limited
788,Asm (area sales manager),5.0,"Aug 3, 2021","Former contractor, more than 3 years",Safaricom gives you the opportunity to excel i...,"At safaricom, there's little room for growth i..."
42,Frontend developer,4.0,"May 22, 2025","Current employee, more than 3 years",- Very friendly and easy to work with colleagu...,- Too much focus on short term goals\n- work o...
945,Client relationship executive,5.0,"Sep 29, 2020",Current contractor,has good working terms : medical cover,you can work as a contractor for many years be...
1051,Customer service,2.0,"Jan 15, 2022",Current employee,fairly good compenastion interms of salary,You will never be promoted for your hardwork u...
160,Software engineer,4.0,"Nov 26, 2024","Current employee, more than 5 years","Good working environment\nDays off, sick leave...",Can be repetitive day in day out
1089,Customer care specialist,4.0,"May 18, 2022","Former contractor, more than 3 years",Good working environment and friendly colleagues,Nothing much only you have to deliver
193,Finance manager,5.0,"Oct 25, 2024","Current contractor, more than 8 years","money money money, more money ...food","large, large large large large"
427,Intern,4.0,"Dec 29, 2023",Former intern,The company was good a stepping stone .,It was an unpaid internship
464,Data scientist,5.0,"Oct 31, 2023","Current employee, more than 3 years",Great work life balance Inclusive work culture...,Salary not at industry level

# Data cleaning.

In [10]:
column1 = data["Job Title"]
column1

0              Brand ambassador
1       Senior mobile developer
2               Project manager
3                Ict technician
4                        Intern
                 ...
1405         Anonymous employee
1406                     Intern
1407                 Internship
1408         Senior ux designer
1409                     Intern
Name: Job Title, Length: 1410, dtype: object

In [19]:
data.isna().sum()

Job Title      0
Job Ratings    0
time           0
JobStatus      0
Pros           0
Cons           0
dtype: int64