In [1]:
import pandas as pd
import numpy as np

In [15]:
SafRev = pd.read_csv("/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/Automating-Boring-Stuff-with-Python/Safaricom reviews/SafaricomReviews.csv")
SafRev

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Brand ambassador,5.0,"Aug 8, 2025","Former employee, more than 1 year","Flexible hours, supportive team, good training...","Inconsistent hours, limited career growth, com..."
1,Senior mobile developer,4.0,"Jul 28, 2025","Current contractor, more than 1 year",Great for gaining experience on large scale en...,A lot of shifting priorities
2,Project manager,4.0,"Jul 15, 2025","Former employee, more than 3 years",Strong support for professional growth through...,Occasional tight deadlines and high-pressure t...
3,Ict technician,5.0,"Jul 18, 2025",Former employee,the working experience was good,there are no major drawbacks i can talk about
4,Intern,5.0,"Jul 15, 2025","Former intern, less than 1 year",Great work environment. Regular bonuses.,None I can think of
...,...,...,...,...,...,...
1405,Anonymous employee,3.0,"Mar 7, 2022","Current employee, more than 1 year",A good place to work,Being overworked and under high pressure
1406,Intern,4.0,"Apr 8, 2022","Former intern, less than 1 year",Good Benefits and Minimal Workload.,Poor structure for internship programme.
1407,Internship,5.0,"Jun 13, 2022",Current intern,Good experience working at safaricom,Could pay interns better atleast
1408,Senior ux designer,2.0,"Jun 20, 2022",Former employee,Good work place to work in Kenya,No cons here in kenya
1409,Intern,5.0,"Aug 16, 2022",Current intern,Good Salary for an intern,none that I came across

In [16]:
# EDA on the data
def display(x):
    print("Displays the rows and columns in the dataset")
    print("============================================")
    Rows, col = x.shape
    print(f"Rows: {Rows} Columns: {col}")
    print()
    print("Displays data columns")
    print("============================================")
    print(x.columns)
    print()
    print("Returns the data information")
    print("============================================")
    print(x.info)
    print()
    print("Returns the information in more details")
    print("============================================")
    print(x.describe())
    print()
    print("The data type")
    print("============================================")
    print(x.dtypes)
    print()
    print("The number of null values in the dataset")
    print("============================================")
    print(x.isna().sum())
display(SafRev)

Displays the rows and columns in the dataset
============================================
Rows: 1410 Columns: 6

Displays data columns
============================================
Index(['Job Title', 'Job Ratings', 'time', 'JobStatus', 'Pros', 'Cons'], dtype='object')

Returns the data information
============================================
<bound method DataFrame.info of                     Job Title  Job Ratings          time  \
0            Brand ambassador          5.0   Aug 8, 2025
1     Senior mobile developer          4.0  Jul 28, 2025
2             Project manager          4.0  Jul 15, 2025
3              Ict technician          5.0  Jul 18, 2025
4                      Intern          5.0  Jul 15, 2025
...                       ...          ...           ...
1405       Anonymous employee          3.0   Mar 7, 2022
1406                   Intern          4.0   Apr 8, 2022
1407               Internship          5.0  Jun 13, 2022
1408       Senior ux designer          2.0  Jun 20, 2022
1409                   Intern          5.0  Aug 16, 2022

                                 JobStatus  \
0        Former employee, more than 1 year
1     Current contractor, more than 1 year
2       Former employee, more than 3 years
3                          Former employee
4          Former intern, less than 1 year
...                                    ...
1405    Current employee, more than 1 year
1406       Former intern, less than 1 year
1407                        Current intern
1408                       Former employee
1409                        Current intern

                                                   Pros  \
0     Flexible hours, supportive team, good training...
1     Great for gaining experience on large scale en...
2     Strong support for professional growth through...
3                       the working experience was good
4              Great work environment. Regular bonuses.
...                                                 ...
1405                               A good place to work
1406                Good Benefits and Minimal Workload.
1407               Good experience working at safaricom
1408                   Good work place to work in Kenya
1409                          Good Salary for an intern

                                                   Cons
0     Inconsistent hours, limited career growth, com...
1                          A lot of shifting priorities
2     Occasional tight deadlines and high-pressure t...
3         there are no major drawbacks i can talk about
4                                   None I can think of
...                                                 ...
1405           Being overworked and under high pressure
1406           Poor structure for internship programme.
1407                   Could pay interns better atleast
1408                              No cons here in kenya
1409                            none that I came across

[1410 rows x 6 columns]>

Returns the information in more details
============================================
       Job Ratings
count  1410.000000
mean      4.238298
std       0.861581
min       1.000000
25%       4.000000
50%       4.000000
75%       5.000000
max       5.000000

The data type
============================================
Job Title       object
Job Ratings    float64
time            object
JobStatus       object
Pros            object
Cons            object
dtype: object

The number of null values in the dataset
============================================
Job Title      0
Job Ratings    0
time           0
JobStatus      0
Pros           0
Cons           0
dtype: int64

In [17]:
# printing the first 20 elements on the dataset
SafRev.head(20)

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Brand ambassador,5.0,"Aug 8, 2025","Former employee, more than 1 year","Flexible hours, supportive team, good training...","Inconsistent hours, limited career growth, com..."
1,Senior mobile developer,4.0,"Jul 28, 2025","Current contractor, more than 1 year",Great for gaining experience on large scale en...,A lot of shifting priorities
2,Project manager,4.0,"Jul 15, 2025","Former employee, more than 3 years",Strong support for professional growth through...,Occasional tight deadlines and high-pressure t...
3,Ict technician,5.0,"Jul 18, 2025",Former employee,the working experience was good,there are no major drawbacks i can talk about
4,Intern,5.0,"Jul 15, 2025","Former intern, less than 1 year",Great work environment. Regular bonuses.,None I can think of
5,Site reliability engineer,4.0,"Jul 14, 2025","Current contractor, more than 1 year",RTO policy 3 days in the office,Workload may be too much sometime
6,Software qa engineer,3.0,"Jul 13, 2025","Former contractor, more than 3 years",Opportunities for growth\nGood company \nGreat...,Tough management \nExtreme work conditions (pr...
7,Customer service,4.0,"Jul 8, 2025","Former intern, less than 1 year",Good place to work and grow career-wise,Is place that offers carrier growth
8,Customer service representative,3.0,"Jul 3, 2025",Current employee,Job security\nBonus is available,No growth\nCompensation for customer care is n...
9,Ran engineer,4.0,"Jul 6, 2025",Former employee,Conducive work environment for employees growth,Have to meet strict deadlines
10,Territory development representative (tdr),4.0,"Jun 28, 2025","Current employee, more than 1 year",Salaries paid on time\nFamiliar route plan,Working via agency\nNo room for growth
11,Telesales agent,5.0,"Jun 26, 2025",Former employee,Good work environment and aesthetics,Corporate work pressure and politics
12,Customer service representative,4.0,"May 25, 2025","Former contractor, more than 1 year",Safaricom really cares about her employees' we...,How I wish they could intervene in the pay and...
13,Junior software developer,5.0,"Jun 7, 2025",Former employee,Good work-life balance and supportive team env...,Limited advancement opportunities and outdated...
14,Sr. manager it,5.0,"Jun 5, 2025",Former employee,"As an employer, offers significant advantages ...","High-pressure, competitive, and sometimes bure..."
15,Software developer,2.0,"Jun 18, 2025","Current contractor, more than 3 years",I really don't have any pros for them. Hasn't ...,no work life balance.\nscalling is almost impo...
16,Ict technician,4.0,"Jun 20, 2025","Current employee, less than 1 year",you Offer the best services,there are No cons about your performance
17,Intern,5.0,"Jun 5, 2025","Former intern, less than 1 year",They try to help interns and the managers are ...,It requires to put a lot effort and sometimes ...
18,Internship,5.0,"Jun 16, 2025",Former intern,Learning and skill building on enterprise leve...,None that I noticed. Good working place.
19,Senior software engineer,5.0,"Jun 11, 2025",Current contractor,to be updated at a later time,none i can think of right now

In [18]:
# printing the last 20 elements on the dataset
SafRev.tail(20)

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
1390,Customer experience executive,5.0,"Oct 20, 2019","Current employee, more than 8 years",Safaricom PLC is a great employer,Career growth is limited
1391,Software engineer,3.0,"Feb 25, 2020","Former contractor, more than 3 years","Average Pay, Nice Projects, Highly engaging","Excess Work hours, Tight Deadlines"
1392,Product manager,5.0,"Oct 30, 2020","Former employee, more than 3 years","Good employer, great environment. Good","Pressure , though performance based"
1393,Engineer,4.0,"Dec 9, 2020","Current employee, more than 1 year",Great team to work with.,High pressure to meet deadlines
1394,Full stack developer,3.0,"Dec 15, 2020",Former employee,nice working with safaricom man,lots of mistakes from them ni wezi
1395,Software engineer,4.0,"Dec 26, 2020","Current employee, more than 3 years",Wonderful place to work as usual,No comment on the issue
1396,Network optimization engineer,5.0,"Feb 3, 2021",Current employee,Very good terms of employment,Slow career growth in technology
1397,Customer experience executive,5.0,"Feb 22, 2021","Former employee, more than 5 years",Good compensation. Diversity and Inclusion,Limited growth within 5 years
1398,Customer experience representative,2.0,"Mar 11, 2021",Former contractor,Company name is the only big thing,"No exposure,to contracted stuff controlling boss"
1399,Information technology,3.0,"Apr 14, 2021",Former temporary employee,efficient in communication sector in Kenya,luring customers to buy their bundles
1400,Legal officer,3.0,"May 13, 2021","Current employee, more than 5 years","Good salary, environment, benefits, offices ar...","Bad bosses, no career advancement"
1401,Telecommunications engineering specialist,4.0,"Jun 13, 2021","Current contractor, more than 8 years",Excellent company to be in,A lot tasks are in place
1402,Customer care representative,2.0,"Jun 19, 2021",KEY NOT FOUND: jobLine.seasonal-former,good company very efficient and fast,poor wadges and late payment rates
1403,Sales representative,5.0,"Oct 4, 2021",Current contractor,Effective communication\r\nTeam work\r\nCoachi...,Growth opportunities are not clear
1404,Account manager,4.0,"Jan 26, 2022",Current employee,Safaricom has good medical benefits,Safaricom Hr processes are very bureacratic
1405,Anonymous employee,3.0,"Mar 7, 2022","Current employee, more than 1 year",A good place to work,Being overworked and under high pressure
1406,Intern,4.0,"Apr 8, 2022","Former intern, less than 1 year",Good Benefits and Minimal Workload.,Poor structure for internship programme.
1407,Internship,5.0,"Jun 13, 2022",Current intern,Good experience working at safaricom,Could pay interns better atleast
1408,Senior ux designer,2.0,"Jun 20, 2022",Former employee,Good work place to work in Kenya,No cons here in kenya
1409,Intern,5.0,"Aug 16, 2022",Current intern,Good Salary for an intern,none that I came across

In [19]:
# printing the random sample of 20 elements
SafRev.sample(20)

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
1304,Research associate,4.0,"Jul 20, 2021",Current employee,good working conditions and overall pay.,the schedule is not flexible.
34,Sr. manager it,5.0,"Jun 5, 2025",Former employee,"As an employer, offers significant advantages ...","High-pressure, competitive, and sometimes bure..."
1382,Customer service representative,5.0,"Feb 5, 2022",Current employee,Salo comes on time sometimes,Mistreating employees who are on contract
454,Solutions architect,5.0,"Nov 19, 2023","Former employee, more than 1 year",Flexibility of work and maximum benefits,Too much work load especially weekends
796,Government affairs manager,5.0,"Oct 15, 2017","Current employee, more than 5 years","Innovative, vibrant place to work with opport...",The rating sysyem is okay though I think the b...
42,Frontend developer,4.0,"May 22, 2025","Current employee, more than 3 years",- Very friendly and easy to work with colleagu...,- Too much focus on short term goals\n- work o...
99,Internship,4.0,"Mar 14, 2025",Current intern,It's good. I enjoyed my time there.,They should pay more to the interns.
1371,Operations manager,5.0,"Apr 27, 2021",Current employee,Lovely best interesting experience good people.,"Busy,busy busy busy busy busy"
260,Internship,4.0,"Aug 6, 2024","Current intern, less than 1 year",Great Perks\nAwesome Staff\nRevolutionary lead...,Bureaucracy in some of the processes
1400,Legal officer,3.0,"May 13, 2021","Current employee, more than 5 years","Good salary, environment, benefits, offices ar...","Bad bosses, no career advancement"
779,Quality analyst,2.0,"Mar 28, 2021","Former employee, more than 3 years",Yearly Bonus \r\nWork from home \r\nGreat trai...,Contract workers are overworked and underpaid ...
372,Internship,5.0,"Feb 27, 2024","Current intern, less than 1 year",Career growth allowing for better opportunities,High competition for places in the company
1363,Software developer intern,4.0,"Oct 4, 2020","Current intern, less than 1 year","Amazing Team, Cool work culture","Slow decision-making process, Too much micro-m..."
119,Software engineer,5.0,"Feb 12, 2025","Current employee, more than 1 year",Hospitable and supportive in career and person...,Very busy and no overtime pay
1012,Digital product manager,4.0,"Aug 20, 2020","Current employee, more than 3 years",Interesting new idea come through the door all...,slow adoption of new ideas by the business
1126,Solutions architect,4.0,"Aug 20, 2019","Current contractor, more than 3 years",Good work environment\r\nAwesome people to wor...,No good flow of work
1360,Customer support representative,5.0,"Aug 20, 2020",Current employee,"Amazing company, good support to employees",None at the moment .
1295,Intern,4.0,"Feb 1, 2021","Current intern, more than 1 year",Fantastic learning and growth opportunities,Highly competitive and fast paced environment ...
696,Software engineer,5.0,"Jan 21, 2023",Former employee,Best tech company in Kenya,Relatively lower pay compared to multinational...
375,Customer service representative,5.0,"Mar 11, 2024","Current employee, more than 5 years",Flexible work environment\nCompetitive salary,Not applicable\nNot applicable \nNot applicable

# Data cleaning.

In [20]:
column1 = SafRev["Job Title"]
column1

0              Brand ambassador
1       Senior mobile developer
2               Project manager
3                Ict technician
4                        Intern
                 ...
1405         Anonymous employee
1406                     Intern
1407                 Internship
1408         Senior ux designer
1409                     Intern
Name: Job Title, Length: 1410, dtype: object

In [21]:
SafRev.isna().sum()

Job Title      0
Job Ratings    0
time           0
JobStatus      0
Pros           0
Cons           0
dtype: int64

In [22]:
# dropping dublicate values
SafRev.dropna(inplace=True)

In [23]:
# changing the datatype of the time column
SafRev['time'] = pd.to_datetime(SafRev['time'], format='%b %d, %Y')

In [25]:
# Rename the headers
SafRev.rename(columns={"Job Title":"Job Title", "Job Ratings":"Job Rating", "time":"Time", "JobStatus":"Job Status",
                      "Pros":"Pros","Cons":"Cons"},inplace=True)

In [38]:
SafRev["Job Title"].unique()

array(['Brand ambassador', 'Senior mobile developer', 'Project manager',
       'Ict technician', 'Intern', 'Site reliability engineer',
       'Software qa engineer', 'Customer service',
       'Customer service representative', 'Ran engineer',
       'Territory development representative (tdr)', 'Telesales agent',
       'Junior software developer', 'Sr. manager it',
       'Software developer', 'Internship', 'Senior software engineer',
       'Software engineer', 'Frontend developer', 'Brand manager',
       'Data analyst', 'Field engineer', 'Territory manager',
       'Customer experience representative', 'Finance intern',
       'Office administrator', 'Consultant', 'Software engineer i',
       'Call center agent', 'Driver', 'Sales associate',
       'Customer service representative (csr)',
       'Consumer business intern', 'Systems engineer',
       'Sales representative', 'Global management trainee (gmt)',
       'Cybersecurity internship', 'Manager', 'Analyst',
       'Administrative assistant', 'Assistant project manager',
       'Data entry clerk', 'Network engineer', 'Cyber security analyst',
       'Audit associate', 'Specialist', 'It specialist',
       'Program manager', 'Backend engineer', 'Finance',
       'Data analyst intern', 'Integration engineer', 'Sales assistant',
       'Solutions architect', 'Legal intern', 'Sre/devops engineer',
       'Contractor', 'Agribusiness manager', 'Ux designer',
       'Data analytics partner', 'Trade development representative',
       'It contractor', 'Software developer intern',
       'Senior assurance officer', 'Graduate trainee', 'Web developer',
       'Customercare executive', 'Admin intern', 'Account executive',
       'Business analyst', 'Customer care representative', 'Qa engineer',
       'Data analyst/junior data scientist', 'Treasury analyst',
       'Customer success manager', 'Engineer', 'It manager',
       'Devops engineer', 'Senior data analyst', 'Team leader',
       'Ml engineer', 'Sofatware engineer', 'Manager, financial services',
       'Sales executive', 'Human resources assistant',
       'Customer experience executive', 'Customer service agent',
       'Data associate', 'Quality engineer', 'Category manager',
       'Computer science/engineering', 'Front end developer',
       'Technology intern', 'Finance manager', 'Data scientist',
       'Senior service reliability engineer', 'Business development',
       'Structural engineer', 'Administrative', 'Management trainee',
       'Site reliability engineer intern', 'Cybersecurity analyst',
       'Backend developer', 'Software engineer(internship)',
       'Engineering manager', 'Database administrator', 'Accountant',
       'Agile coach', 'Marketing coordinator', 'Cybersecurity',
       'Vas engineer', 'Ran capacity planning engineer',
       'Accounts payable', 'Principal auditor', 'Commercial manager',
       'Field agent', 'Customer care specialist',
       'Senior executive assistant', 'Finance team lead',
       'Senior integration engineer',
       'Software development engineer in test (sdet)', 'Sales',
       'Android developer', 'Graphic designer', 'Account manager',
       'Customer support specialist', 'Ip support engineer',
       'Full stack engineer', 'Data engineer',
       'Çustomer service representative', 'Senior solutions architect',
       'Front desk agent', 'Telecom engineer', 'Data entry',
       'Call center representative', 'Technical lead',
       'Lead android developer', 'Senior cse', 'Telesales representative',
       'Ftth engineer', 'Customer service account associate',
       'Anonymous contractor', 'Human resources manager',
       'Senior network engineer', 'Solutions engineer',
       'Casual team member', 'Technician', 'Bi developer',
       'Network administrator', 'Senior data analytics engineer',
       'It intern', 'Middle ios developer',
       'Client relationship executive', 'Accounts assistant',
       'Systems administrator', 'Radio access network engineer',
       'It assistant', 'Software engineer intenship', 'Marketing intern',
       'Product manager', 'Senior software developer', 'It technician',
       'Chef', 'Direct sales representative',
       'It technical support specialist', 'Business development manager',
       'Marketing', 'Tdr trade development representative',
       'Anonymous employee', 'Band h', 'Program director',
       'Enterprise risk management', 'Digital marketing',
       'Accounts receivable', 'Microservices developer',
       'Product designer', 'Financial services intern', 'Human resources',
       'Human resources specialist (hr specialist)',
       'Machine learning engineer', 'Cloud support engineer',
       'Quality assurance', 'Junior data analyst',
       'Senior manager international business', 'Janitor/cleaner',
       'Software engineer intern', 'Technical support engineer',
       'Chief technology officer (cto)', 'Principal',
       'Graduate engineer trainee', 'Support analyst',
       'Market researcher', 'Qaengineer', 'Enterprise support engineer',
       'Online chat agent', 'Sales officer', 'Chat moderator',
       'Principal engineer', 'Software development engineer (sde)',
       'Scrum master/agile coach', 'Merchant support', 'Intern engineer',
       'Chief executive officer (ceo)', 'Product owner',
       'Big data engineer', 'Analysts', 'Is intern', 'Ict officer',
       'Customer care executive', 'Sales manager', 'Security guard',
       'Pricing analyst', 'Accounts clerk', 'Senior graphic designer',
       'Sales represenative', 'Fixed support central dispatch engineer',
       'Sales agent', 'Cloud engineer', 'Software engineer ii',
       'Solution architect', 'Computer programmer', 'Soc engineer',
       'Customer experience specialist', 'Customer sevice specialist',
       'Sales intern', 'Analytics manager', 'Financial controller',
       'End user support', 'Communications',
       'Financial services representative', 'Saler support',
       'Frontend web developer', 'Category sourcing manager',
       'Head of technical', 'Sweeper', 'Treasury intern',
       'Dealer relationship manager', 'Tech leader', 'Hod',
       'Fullstack developer', 'Network intern', 'Integrations engineer',
       'Paid ads specialist', 'Database administrator (dba)',
       'Social media manager', 'Tech support engineer',
       'Asm (area sales manager)', 'Junior software engineer',
       'Communications manager', 'Ict manager',
       'Field sales representative', 'It business analyst',
       'Customer care', 'Direct sales agent', 'Marketing specialist',
       'It support', 'Ui-ux designer & graphics designer',
       'Vas support engineer', 'Supervisor', 'Data base administrator',
       'Graduate management engineer', 'Software engineering',
       'Senior engineer', 'Business data analyst',
       'Discover-graduate program', 'Financial analyst',
       'Head of research', 'Data manager', 'Accounts intern',
       'Senior manager enterprise service delivery',
       'Principal radio planning engineer', 'Retail analyst',
       'Mid level manager', 'Human resources officer',
       'Security controller', 'Senior manager - retail transformation',
       'Ipcc engineer', 'Senior management', 'Corporate ressponsibility',
       'Procurement intern', 'Training coordinator',
       'Consulting hardware engineer', 'Sales executives',
       'Technology academy', 'Project deployment',
       'Telecommunications engineer', 'Management engineer',
       'Core network engineer', 'Hrbp', 'Retail cee',
       'Technical project manager', 'Territory account executive',
       'Enterprise infrastructure', 'Quality analyst',
       'Social media analyst', 'Customer experience manager',
       'Senior manager', 'Sector manager', 'Government affairs manager',
       'Support lead', 'Retail customer experience executive',
       'Anonymous intern', 'Computer science student',
       'Data science intern', 'Information security analyst',
       'Senior manager innovation', 'Technology analyst',
       'Senior officer', 'Route salesman', 'Junior data scientist',
       'Manager, operations', 'Human resources consultant',
       'Bi management', 'Integration support analyst',
       'Acting inbound logistics manager',
       'Telecommunications (oss) engineer', 'Product marketer',
       'Enterprise provisioning', 'Principal operations officer',
       'Retail assistant - customer services', 'Women in technology',
       'Sales and marketing', 'Engineering internship',
       'Senior devops engineer',
       'Principal human resource business partner (hrbp) officer',
       'Regional sales manager', 'Segments manager', 'Office assistant',
       'Platinum support manager', 'Business development associate',
       'Principal internal auditor', 'Dealer manager',
       'Softeware engineer', 'Quality assurance analyst', 'Hr-intern',
       'Corporate sales', 'Logistics quality assurance',
       'It support analyst', 'Bi analyst', 'Relationship manager',
       'Call centre team leader', 'Territory account manager',
       'Senior manager operations engineering', 'Systems analyst',
       'Principal analyst', 'Call center customer service representative',
       'Customer service associate', 'Finance professional',
       'Senior officer, supplier qualification and contracts management',
       'Products development engineer', 'Supply chain',
       'User experience designer', 'Chief executive officer',
       'Ip planning engineer', 'Software development intern',
       'Intraoperative neuromonitoring tech',
       'Trade Development Representative', 'Stock controller', 'Coder',
       'Configuration and support engineer', 'Inventory controller',
       'Nairobi', 'Customer executive officer',
       'Graduate electrical engineer', 'Projects officer',
       'Cloud solutions engineer', 'Senior iot engineer',
       'Personal assistant', 'Digital customer experience manager',
       'Qa governance & operations', 'Applications support engineer',
       'Intern - hourly', 'Kenya – republic of kenya',
       'Technical consultant', 'Digital product manager',
       'Provisioning engineer', 'Assistant store manager',
       'Software engineer - android', 'Tdr - sales', 'Fibre technician',
       'Senior scrum master', 'Ass treasurer', 'Compliance manager',
       'Senior customer service representative',
       'Talent acquisition specialist',
       'Capital projects business partner', 'Operations team leader',
       'Network officer', 'Procurement analyst', 'Networking engineer',
       'Business executive', 'Secretary', 'Radio planning engineer',
       'Financial advisor', 'Ran', 'Product development',
       'National account manager', 'Computer systems engineer',
       'Senior human resources officer', 'Retention manager',
       'Programme analyst', 'Senior principal developer',
       'Procurement officer', 'Operations engineer', 'Staff accountant',
       'Senior product manager', 'Enterprise service desk engineer',
       'Retail quality analyst', 'Remote support engineer',
       'Customer service specialist', 'Talent acquisition intern',
       'Assistant commercial manager', 'It incident management analyst',
       'Data analyst/data scientist', 'Senior tech lead',
       'Student intern', 'Junior graphic designer',
       'Ran optimization and planning engineer',
       'Commercial sales consultant', 'Senior accountant',
       'Service assurance engineer', 'Digital experience executive',
       'Cyber security consultant', 'Call centre agent',
       'Devops/full-stack developer', 'Marketer', 'Ip engineer',
       'Advertising sales or data entry', 'Technical enterprise services',
       'Senior sourcing engineer', 'Ict', 'Anonymous temporary employee',
       'Contact center team leader', 'Digital media executive',
       'Technology', 'Risk management', 'Project management intern',
       'Social worker', 'Customer support', 'Site administrator',
       'Qa intern', 'Software quality assurance engineer',
       'Sales manager cee', 'Writer', 'Territory sales representative',
       'Network planning engineer', 'Business engagement manager',
       'Lead engineer', 'Senior communications manager',
       'Enterprise quality assurance analyst', 'Typing',
       'Resource planning analyst', 'Content marketer', 'Cyber security',
       'It solutions architect', 'Stock control',
       'Computer scientist (1550)', 'Field service engineer',
       'Manager - new business development', 'Cleaning',
       'Django developer', 'Executive assistant', 'Inventory accountant',
       'Finance/accounting', 'Delear sales associate',
       'Systems developer', 'Noc engineer', 'Product development manager',
       'Research associate', 'Online data entry', 'Brand promotion',
       'Actuarial analyst', 'Legal assistant', 'Designer',
       'Stocks controller', 'Core network support',
       'Intern for financial services', 'Customer service executive',
       'I t analyst', 'Senior software engineer/tech lead',
       'Mobile developer', 'Internal auditor',
       'Financial service operator', 'Senior financial services officer',
       'Customer support representative',
       'Regional business development manager',
       'Sales, marketing and communications professional', 'Mpesa',
       'Senior lawyer', 'Operations manager', 'Relationship officer',
       'Retail centre team leader', 'Executive', 'Itspecialist',
       'Brand experience activations manager', 'Full stack developer',
       'Network optimization engineer', 'Information technology',
       'Legal officer', 'Telecommunications engineering specialist',
       'Senior ux designer'], dtype=object)

In [39]:
# rename detail
SafRev["Job Title"].replace({"Software qa engineer":"Software Engineer"}, inplace=True)

In [37]:
# locating value on the dataset
SafRev[SafRev["Job Title"]=="Software qa engineer"]

,Job Title,Job Rating,Time,Job Status,Pros,Cons
944,Trade Development Representative,5.0,2019-02-20,"Former employee, more than 1 year",took care for their workers at all times,medical cover from agencies always came in late
1220,Trade Development Representative,5.0,2020-10-31,Formerly self-employed,Safaricom is the best co.,Work is sometimes hectic k